#!/bin/bash

url=$1

if [ -z "$url" ]; then
    echo "Uso: $0 <url>"
    exit 1
fi


echo "[+] Baixando HTML de $url..."
html=$(curl -s "$url")


echo
echo "DOMÍNIO                         IP"
echo "---------------------------------------------"


echo "$html" | \
grep -oE 'https?://[a-zA-Z0-9.-]+' | \
awk -F/ '{print $3}' | \
sort -u | \
while read dominio
do
    ip=$(dig +short "$dominio" | head -n 1)

    if [ ! -z "$ip" ]; then
        printf "%-30s %s\n" "$dominio" "$ip"
    fi
done
